@startuml singletonMONE
!theme plain
skinparam linetype ortho

class RouteService {
    - static instance: RouteService
    - constructor(deps?: RouteServiceDeps)
    + static getInstance(deps?: RouteServiceDeps): RouteService
    + requestRoute(options): Promise<IRouteData>
    + saveRoute(options): Promise<string>
}

class RouteFacade {
    - service: RouteService
    + constructor(deps?)
    + requestRoute(...)
}

RouteFacade --> RouteService : usa RouteService.getInstance()

@enduml
